on: [push]
jobs:
  test:
    runs-on: debian-bookworm

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependecies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends --no-upgrade -y just

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
