on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04

    - name: Install system dependecies
      run: |
        apt update
        apt install --no-install-recommends --no-upgrade -y git node

    - name: Install dependecies
      run: |
        apt install --no-install-recommends --no-upgrade -y just

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
