on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Install system dependecies
      run: |
        apt update
        apt install --no-install-recommends --no-upgrade -y git nodejs curl ca-certificates

    - name: Check connectivity
      run: |
        curl -v https://forge.aizatsky.com/

    - name: Install dependecies
      run: |
        apt install --no-install-recommends --no-upgrade -y just gnupg libassuan-dev libgpgme-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: just build

    # TODO
    # - name: Test
    #   run: just test

    - name: Release Artifacts
      run: just release $(git describe --tags)

