name: Build

on:
  push:
    branches: [ "master" ]
    tags: ["*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependecies
      run: |
        sudo apt remove needrestart
        sudo apt update
        sudo apt install --no-install-recommends --no-upgrade -y just

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Release Artifacts
      run: just release $(git describe --tags)

    - name: Archive Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: declix-artifacts.zip
        path: dist/*

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*